# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-19 21:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('adress', models.CharField(max_length=30)),
                ('num_pass', models.IntegerField()),
            ],
        ),
    ]
